# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# frozen_string_literal: true

# stub: ruby_osx_app 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = 'ruby_osx_app'
  s.version = '0.1.1'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['Marcin Nowicki']
  s.date = '2013-12-22'
  s.description = 'This gem operates on Mac OSX Applications to retrieve information from them.'
  s.email = 'pr0d1r2@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    '.document',
    '.rspec',
    '.ruby-version',
    'Gemfile',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'lib/osx_app.rb',
    'ruby_osx_app.gemspec',
    'spec/osx_app_spec.rb',
    'spec/rails_best_practices_spec.rb',
    'spec/rubocop_spec.rb',
    'spec/spec_helper.rb'
  ]
  s.homepage = 'http://github.com/pr0d1r2/ruby_osx_app'
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = '2.1.5'
  s.summary = 'This gem operates on Mac OSX Applications to retrieve information from them.'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_development_dependency('bundler', ['~> 1.0'])
      s.add_development_dependency('jeweler', ['~> 1.8.7'])
      s.add_development_dependency('rails_best_practices', ['>= 0'])
      s.add_development_dependency('rdoc', ['~> 3.12'])
      s.add_development_dependency('rspec', ['~> 2.8.0'])
      s.add_development_dependency('rubocop', ['>= 0'])
      s.add_development_dependency('simplecov', ['>= 0'])
    else
      s.add_dependency('bundler', ['~> 1.0'])
      s.add_dependency('jeweler', ['~> 1.8.7'])
      s.add_dependency('rails_best_practices', ['>= 0'])
      s.add_dependency('rdoc', ['~> 3.12'])
      s.add_dependency('rspec', ['~> 2.8.0'])
      s.add_dependency('rubocop', ['>= 0'])
      s.add_dependency('simplecov', ['>= 0'])
    end
  else
    s.add_dependency('rspec', ['~> 2.8.0'])
    s.add_dependency('rspec', ['~> 2.8.0'])
    s.add_dependency('rspec', ['~> 2.8.0'])
    s.add_dependency('rspec', ['~> 2.8.0'])
    s.add_dependency('simplecov', ['>= 0'])
    s.add_dependency('simplecov', ['>= 0'])
    s.add_dependency('simplecov', ['>= 0'])
  end
end
